version: '3'

services:
  emqx:
    image: emqx/emqx:4.2.7
    environment:
    - "EMQX_NAME=emqx"
    - "WAIT_FOR_ERLANG=60"
    volumes:
      - ./data/loaded_plugins:/opt/emqx/data/loaded_plugins
      - ./emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf
    ports:
    - 1883:1883
    - 8081:8081
    - 18083:18083
  
