version: '3.7'
services:
  postgresql:
    image: postgres
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    network_mode: host
    environment:
    - "PGADMIN_LISTEN_PORT=81"
    ports:
    - "81:80"
    volumes:
    - ./servers.json:/pgadmin4/servers.json
    restart: always

volumes:
  db-data:
    driver: local
